#!/usr/bin/env bash
# OneMuseum v1.0.4 — static asset cleanup
# Removes 375 unreferenced theme images (~75.7 MB) from onemuseum/static/
#
# Verified by reference audit: every filename below was checked against all
# .html/.css/.scss/.js/.py/.json/.md/.txt files in the project. None appear.
#
# KEPT (referenced in live templates):
#   assets/img: bg6.jpg, blurred-image-1.jpg, olivia.jpg, logo.png, apple-icon.png
#   img:        sheng-li-*.jpg, belinda-fewings-*.jpg, staryellow.png,
#               starempty.png, icons8-museum-30.png
#
# NOT TOUCHED: assets/css, assets/js, assets/scss, assets/fonts,
#              nucleoicons/, profile_pics/  — all live or user data.
#
# Usage:  bash cleanup_static.sh          (dry run, lists what would go)
#         bash cleanup_static.sh --commit (actually deletes)

set -euo pipefail
cd "$(dirname "$0")"

if [[ ! -d onemuseum/static ]]; then
  echo "ERROR: run this from the repository root (onemuseum/static not found)." >&2
  exit 1
fi

COMMIT=0
[[ "${1:-}" == "--commit" ]] && COMMIT=1

# --- Group 1: vendor demo directories (~29 MB) -------------------------------
DEMO=(
  "static/assets/img/examples/card-blog10 (Thumb).jpg"
  "static/assets/img/examples/card-blog10.jpg"
  "static/assets/img/examples/card-blog11.jpg"
  "static/assets/img/examples/card-blog12 (Thumb).jpg"
  "static/assets/img/examples/card-blog12.jpg"
  "static/assets/img/examples/card-blog13 (Thumb).jpg"
  "static/assets/img/examples/card-blog13.jpg"
  "static/assets/img/examples/card-blog14.jpg"
  "static/assets/img/examples/card-blog15.jpg"
  "static/assets/img/examples/card-blog16 (Thumb).jpg"
  "static/assets/img/examples/card-blog16.jpg"
  "static/assets/img/examples/card-blog17.jpg"
  "static/assets/img/examples/card-blog18 (Thumb).jpg"
  "static/assets/img/examples/card-blog18.jpg"
  "static/assets/img/examples/card-blog4.jpg"
  "static/assets/img/examples/card-blog5.jpg"
  "static/assets/img/examples/card-blog6.jpg"
  "static/assets/img/examples/card-blog7.jpg"
  "static/assets/img/examples/card-blog9.jpg"
  "static/assets/img/examples/card-profile1.jpg"
  "static/assets/img/examples/card-profile2 (Thumb).jpg"
  "static/assets/img/examples/card-profile2.jpg"
  "static/assets/img/examples/card-profile3.jpg"
  "static/assets/img/examples/card-project1.jpg"
  "static/assets/img/examples/office1.jpg"
  "static/assets/img/presentation-page/Pages/about-us.jpg"
  "static/assets/img/presentation-page/Pages/blog-post.jpg"
  "static/assets/img/presentation-page/Pages/blog-posts.jpg"
  "static/assets/img/presentation-page/Pages/contact.jpg"
  "static/assets/img/presentation-page/Pages/ecommerce.jpg"
  "static/assets/img/presentation-page/Pages/landing.jpg"
  "static/assets/img/presentation-page/Pages/login.jpg"
  "static/assets/img/presentation-page/Pages/pricing.jpg"
  "static/assets/img/presentation-page/Pages/product.jpg"
  "static/assets/img/presentation-page/Pages/profile.jpg"
  "static/assets/img/presentation-page/Pages/signup.jpg"
  "static/assets/img/presentation-page/basic_thumb.jpg"
  "static/assets/img/presentation-page/bg50.jpg"
  "static/assets/img/presentation-page/blogpost1.jpg"
  "static/assets/img/presentation-page/blogpost2.jpg"
  "static/assets/img/presentation-page/blogpost3.jpg"
  "static/assets/img/presentation-page/blogpost4.jpg"
  "static/assets/img/presentation-page/blogpost5.jpg"
  "static/assets/img/presentation-page/card1.jpg"
  "static/assets/img/presentation-page/card2.png"
  "static/assets/img/presentation-page/card3.jpg"
  "static/assets/img/presentation-page/card4.jpg"
  "static/assets/img/presentation-page/card5.jpg"
  "static/assets/img/presentation-page/card6.jpg"
  "static/assets/img/presentation-page/card7.jpg"
  "static/assets/img/presentation-page/cards_thumb.jpg"
  "static/assets/img/presentation-page/coloured-card-with-btn.jpg"
  "static/assets/img/presentation-page/coloured-card.jpg"
  "static/assets/img/presentation-page/contact1.jpg"
  "static/assets/img/presentation-page/contact2.jpg"
  "static/assets/img/presentation-page/content1.jpg"
  "static/assets/img/presentation-page/content3.jpg"
  "static/assets/img/presentation-page/content3.png"
  "static/assets/img/presentation-page/content4.jpg"
  "static/assets/img/presentation-page/content4.png"
  "static/assets/img/presentation-page/features1.jpg"
  "static/assets/img/presentation-page/features2.jpg"
  "static/assets/img/presentation-page/features3.jpg"
  "static/assets/img/presentation-page/features4.jpg"
  "static/assets/img/presentation-page/features5.jpg"
  "static/assets/img/presentation-page/features6.jpg"
  "static/assets/img/presentation-page/features7.jpg"
  "static/assets/img/presentation-page/features8.jpg"
  "static/assets/img/presentation-page/harvard.jpg"
  "static/assets/img/presentation-page/header1.jpg"
  "static/assets/img/presentation-page/header2.jpg"
  "static/assets/img/presentation-page/header3.jpg"
  "static/assets/img/presentation-page/header4.jpg"
  "static/assets/img/presentation-page/header5.jpg"
  "static/assets/img/presentation-page/linkedin-btn.jpg"
  "static/assets/img/presentation-page/microsoft.jpg"
  "static/assets/img/presentation-page/nuk-pro-back-sky-black.jpg"
  "static/assets/img/presentation-page/nuk-pro-back-sky-orange.jpg"
  "static/assets/img/presentation-page/nuk-pro-back-sky.jpg"
  "static/assets/img/presentation-page/nuk-pro-buildings-black.png"
  "static/assets/img/presentation-page/nuk-pro-buildings.png"
  "static/assets/img/presentation-page/pages2_thumb.jpg"
  "static/assets/img/presentation-page/pages_thumb.jpg"
  "static/assets/img/presentation-page/pricing1.jpg"
  "static/assets/img/presentation-page/pricing2.jpg"
  "static/assets/img/presentation-page/pricing3.jpg"
  "static/assets/img/presentation-page/pricing4.jpg"
  "static/assets/img/presentation-page/pricing5.jpg"
  "static/assets/img/presentation-page/projects1.jpg"
  "static/assets/img/presentation-page/projects2.jpg"
  "static/assets/img/presentation-page/projects3.jpg"
  "static/assets/img/presentation-page/projects4.jpg"
  "static/assets/img/presentation-page/projects5.jpg"
  "static/assets/img/presentation-page/sections_thumb.jpg"
  "static/assets/img/presentation-page/share-btn.jpg"
  "static/assets/img/presentation-page/social-row.jpg"
  "static/assets/img/presentation-page/stanford.jpg"
  "static/assets/img/presentation-page/table.jpg"
  "static/assets/img/presentation-page/team1.jpg"
  "static/assets/img/presentation-page/team2.jpg"
  "static/assets/img/presentation-page/team3.jpg"
  "static/assets/img/presentation-page/team4.jpg"
  "static/assets/img/presentation-page/team5.jpg"
  "static/assets/img/presentation-page/testimonials1.jpg"
  "static/assets/img/presentation-page/testimonials2.jpg"
  "static/assets/img/presentation-page/testimonials3.jpg"
  "static/assets/img/presentation-page/vodafone.jpg"
)

# --- Group 2: remaining unreferenced theme images (~47 MB) -------------------
REST=(
  "static/assets/img/avatar.jpg"
  "static/assets/img/balmain.jpg"
  "static/assets/img/bg1.jpg"
  "static/assets/img/bg11.jpg"
  "static/assets/img/bg14.jpg"
  "static/assets/img/bg15.jpg"
  "static/assets/img/bg16.jpg"
  "static/assets/img/bg17.jpg"
  "static/assets/img/bg18.jpg"
  "static/assets/img/bg19.jpg"
  "static/assets/img/bg20.jpg"
  "static/assets/img/bg21.jpg"
  "static/assets/img/bg22.jpg"
  "static/assets/img/bg23.jpg"
  "static/assets/img/bg24.jpg"
  "static/assets/img/bg25.jpg"
  "static/assets/img/bg26.jpg"
  "static/assets/img/bg27.jpg"
  "static/assets/img/bg28.jpg"
  "static/assets/img/bg29.jpg"
  "static/assets/img/bg3.jpg"
  "static/assets/img/bg30.jpg"
  "static/assets/img/bg31.jpg"
  "static/assets/img/bg32.jpg"
  "static/assets/img/bg35.jpg"
  "static/assets/img/bg37.jpg"
  "static/assets/img/bg38.jpg"
  "static/assets/img/bg39.jpg"
  "static/assets/img/bg4.jpg"
  "static/assets/img/bg40.jpg"
  "static/assets/img/bg41.jpg"
  "static/assets/img/bg43.jpg"
  "static/assets/img/bg44 (Thumb).jpg"
  "static/assets/img/bg44.jpg"
  "static/assets/img/bg45.jpg"
  "static/assets/img/bg5.jpg"
  "static/assets/img/bg51.jpg"
  "static/assets/img/bg7.jpg"
  "static/assets/img/bg8.jpg"
  "static/assets/img/bg9.jpg"
  "static/assets/img/blog1.jpg"
  "static/assets/img/boglioli.jpg"
  "static/assets/img/card-blog2 (Thumb).jpg"
  "static/assets/img/card-blog2.jpg"
  "static/assets/img/card-blog3 (Thumb).jpg"
  "static/assets/img/card-blog3.jpg"
  "static/assets/img/contact-us-image.png"
  "static/assets/img/contact1.jpg"
  "static/assets/img/cov1.jpg"
  "static/assets/img/creative-tim-white-slim2.png"
  "static/assets/img/default-avatar.png"
  "static/assets/img/emily.jpg"
  "static/assets/img/emilyz.jpg"
  "static/assets/img/favicon.png"
  "static/assets/img/flags/AD.png"
  "static/assets/img/flags/AE.png"
  "static/assets/img/flags/AG.png"
  "static/assets/img/flags/AM.png"
  "static/assets/img/flags/AR.png"
  "static/assets/img/flags/AT.png"
  "static/assets/img/flags/AU.png"
  "static/assets/img/flags/BE.png"
  "static/assets/img/flags/BF.png"
  "static/assets/img/flags/BG.png"
  "static/assets/img/flags/BO.png"
  "static/assets/img/flags/BR.png"
  "static/assets/img/flags/CA.png"
  "static/assets/img/flags/CD.png"
  "static/assets/img/flags/CG.png"
  "static/assets/img/flags/CH.png"
  "static/assets/img/flags/CL.png"
  "static/assets/img/flags/CM.png"
  "static/assets/img/flags/CN.png"
  "static/assets/img/flags/CO.png"
  "static/assets/img/flags/CZ.png"
  "static/assets/img/flags/DE.png"
  "static/assets/img/flags/DJ.png"
  "static/assets/img/flags/DK.png"
  "static/assets/img/flags/DZ.png"
  "static/assets/img/flags/EE.png"
  "static/assets/img/flags/EG.png"
  "static/assets/img/flags/ES.png"
  "static/assets/img/flags/FI.png"
  "static/assets/img/flags/FR.png"
  "static/assets/img/flags/GA.png"
  "static/assets/img/flags/GB.png"
  "static/assets/img/flags/GM.png"
  "static/assets/img/flags/GT.png"
  "static/assets/img/flags/HN.png"
  "static/assets/img/flags/HT.png"
  "static/assets/img/flags/HU.png"
  "static/assets/img/flags/ID.png"
  "static/assets/img/flags/IE.png"
  "static/assets/img/flags/IL.png"
  "static/assets/img/flags/IN.png"
  "static/assets/img/flags/IQ.png"
  "static/assets/img/flags/IR.png"
  "static/assets/img/flags/IT.png"
  "static/assets/img/flags/JM.png"
  "static/assets/img/flags/JO.png"
  "static/assets/img/flags/JP.png"
  "static/assets/img/flags/KG.png"
  "static/assets/img/flags/KN.png"
  "static/assets/img/flags/KP.png"
  "static/assets/img/flags/KR.png"
  "static/assets/img/flags/KW.png"
  "static/assets/img/flags/KZ.png"
  "static/assets/img/flags/LA.png"
  "static/assets/img/flags/LB.png"
  "static/assets/img/flags/LC.png"
  "static/assets/img/flags/LS.png"
  "static/assets/img/flags/LU.png"
  "static/assets/img/flags/LV.png"
  "static/assets/img/flags/MG.png"
  "static/assets/img/flags/MK.png"
  "static/assets/img/flags/ML.png"
  "static/assets/img/flags/MM.png"
  "static/assets/img/flags/MT.png"
  "static/assets/img/flags/MX.png"
  "static/assets/img/flags/NA.png"
  "static/assets/img/flags/NE.png"
  "static/assets/img/flags/NG.png"
  "static/assets/img/flags/NI.png"
  "static/assets/img/flags/NL.png"
  "static/assets/img/flags/NO.png"
  "static/assets/img/flags/OM.png"
  "static/assets/img/flags/PA.png"
  "static/assets/img/flags/PE.png"
  "static/assets/img/flags/PG.png"
  "static/assets/img/flags/PK.png"
  "static/assets/img/flags/PL.png"
  "static/assets/img/flags/PT.png"
  "static/assets/img/flags/PY.png"
  "static/assets/img/flags/QA.png"
  "static/assets/img/flags/RO.png"
  "static/assets/img/flags/RU.png"
  "static/assets/img/flags/RW.png"
  "static/assets/img/flags/SA.png"
  "static/assets/img/flags/SE.png"
  "static/assets/img/flags/SG.png"
  "static/assets/img/flags/SL.png"
  "static/assets/img/flags/SN.png"
  "static/assets/img/flags/SO.png"
  "static/assets/img/flags/SV.png"
  "static/assets/img/flags/TD.png"
  "static/assets/img/flags/TJ.png"
  "static/assets/img/flags/TL.png"
  "static/assets/img/flags/TR.png"
  "static/assets/img/flags/TZ.png"
  "static/assets/img/flags/UA.png"
  "static/assets/img/flags/US.png"
  "static/assets/img/flags/VE.png"
  "static/assets/img/flags/VN.png"
  "static/assets/img/flags/YE.png"
  "static/assets/img/github.jpg"
  "static/assets/img/gucci.jpg"
  "static/assets/img/header.jpg"
  "static/assets/img/hero-image-1.png"
  "static/assets/img/hero-image-2.png"
  "static/assets/img/hero-image-3.png"
  "static/assets/img/image_placeholder.jpg"
  "static/assets/img/invision-white-slim.png"
  "static/assets/img/ipad.png"
  "static/assets/img/ipad2-inverted.png"
  "static/assets/img/ipad2.png"
  "static/assets/img/ipad3.png"
  "static/assets/img/iphone2.png"
  "static/assets/img/james.jpg"
  "static/assets/img/julie.jpg"
  "static/assets/img/kingsman.jpg"
  "static/assets/img/landing.jpg"
  "static/assets/img/login.jpg"
  "static/assets/img/logo-square.jpg"
  "static/assets/img/marie.jpg"
  "static/assets/img/michael.jpg"
  "static/assets/img/mike.jpg"
  "static/assets/img/now-logo.png"
  "static/assets/img/nucleo-logo.svg"
  "static/assets/img/placeholder.jpg"
  "static/assets/img/polo.jpg"
  "static/assets/img/pp-1.jpg"
  "static/assets/img/pp-2.jpg"
  "static/assets/img/pp-3.jpg"
  "static/assets/img/pp-4.jpg"
  "static/assets/img/pp-5.jpg"
  "static/assets/img/pp-cov.jpg"
  "static/assets/img/prada.jpg"
  "static/assets/img/pricing1.jpg"
  "static/assets/img/pricing2.jpg"
  "static/assets/img/pricing3.jpg"
  "static/assets/img/pricing4.jpg"
  "static/assets/img/product1.jpg"
  "static/assets/img/product2.jpg"
  "static/assets/img/product3.jpg"
  "static/assets/img/profile.jpg"
  "static/assets/img/project1.jpg"
  "static/assets/img/project10.jpg"
  "static/assets/img/project11.jpg"
  "static/assets/img/project12.jpg"
  "static/assets/img/project13.jpg"
  "static/assets/img/project14.jpg"
  "static/assets/img/project15.jpg"
  "static/assets/img/project16.jpg"
  "static/assets/img/project17.jpg"
  "static/assets/img/project18.jpg"
  "static/assets/img/project19.jpg"
  "static/assets/img/project2.jpg"
  "static/assets/img/project20.jpg"
  "static/assets/img/project21.jpg"
  "static/assets/img/project22.jpg"
  "static/assets/img/project23.jpg"
  "static/assets/img/project24.jpg"
  "static/assets/img/project4.jpg"
  "static/assets/img/project5 .jpg"
  "static/assets/img/project5.jpg"
  "static/assets/img/project6.jpg"
  "static/assets/img/project7.jpg"
  "static/assets/img/project8.jpg"
  "static/assets/img/project9.jpg"
  "static/assets/img/ryan.jpg"
  "static/assets/img/saint-laurent.jpg"
  "static/assets/img/saint-laurent1.jpg"
  "static/assets/img/sweeney.jpg"
  "static/assets/img/tom-ford.jpg"
  "static/assets/img/usher.jpg"
  "static/assets/img/wooyoungmi.jpg"
  "static/img/belinda-fewings-_CyyAj0QboY-unsplash (Small).jpg"
  "static/img/belinda-fewings-_CyyAj0QboY-unsplash (Thumb).jpg"
  "static/img/brigitta-schneiter-MHGDVDWjAb4-unsplash (Custom).jpg"
  "static/img/brigitta-schneiter-MHGDVDWjAb4-unsplash (Small).jpg"
  "static/img/brigitta-schneiter-MHGDVDWjAb4-unsplash (Thumb).jpg"
  "static/img/eric-prouzet-jLtXXn7n16k-unsplash (Custom).jpg"
  "static/img/eric-prouzet-jLtXXn7n16k-unsplash (Small).jpg"
  "static/img/eric-prouzet-jLtXXn7n16k-unsplash (Thumb).jpg"
  "static/img/harald-arlander-WZ6gITnjqaQ-unsplash (Custom).jpg"
  "static/img/harald-arlander-WZ6gITnjqaQ-unsplash (Small).jpg"
  "static/img/harald-arlander-WZ6gITnjqaQ-unsplash (Thumb).jpg"
  "static/img/icons8-museum-60.png"
  "static/img/icons8-museum-90.png"
  "static/img/james-l-w-v5gIzrQ_P60-unsplash (Custom).jpg"
  "static/img/james-l-w-v5gIzrQ_P60-unsplash (Small).jpg"
  "static/img/james-l-w-v5gIzrQ_P60-unsplash (Thumb).jpg"
  "static/img/joe-pregadio-k92PS1rFdF4-unsplash (Custom).jpg"
  "static/img/joe-pregadio-k92PS1rFdF4-unsplash (Small).jpg"
  "static/img/joe-pregadio-k92PS1rFdF4-unsplash (Thumb).jpg"
  "static/img/one-museum-1.jpg"
  "static/img/one-museum-2.jpg"
  "static/img/one-museum.jpg"
  "static/img/piotr-kolawa-1Cw_ZbPljZ4-unsplash (Custom).jpg"
  "static/img/piotr-kolawa-1Cw_ZbPljZ4-unsplash (Small).jpg"
  "static/img/piotr-kolawa-1Cw_ZbPljZ4-unsplash (Thumb).jpg"
  "static/img/revolt-m2JlMXdqb3s-unsplash (Custom).jpg"
  "static/img/revolt-m2JlMXdqb3s-unsplash (Small).jpg"
  "static/img/revolt-m2JlMXdqb3s-unsplash (Thumb).jpg"
  "static/img/sandra-grunewald-Zs66DA05TSg-unsplash (Custom).jpg"
  "static/img/sandra-grunewald-Zs66DA05TSg-unsplash (Small).jpg"
  "static/img/scott-webb-ab80p262fFM-unsplash (Custom).jpg"
  "static/img/scott-webb-ab80p262fFM-unsplash (Small).jpg"
  "static/img/scott-webb-ab80p262fFM-unsplash (Thumb).jpg"
  "static/img/sheng-li-AHV8vqJIuqU-unsplash (Small).jpg"
  "static/img/sheng-li-AHV8vqJIuqU-unsplash (Thumb).jpg"
  "static/img/starfilled.png"
  "static/img/susan-yin-2JIvboGLeho-unsplash (Custom).jpg"
  "static/img/susan-yin-2JIvboGLeho-unsplash (Small).jpg"
  "static/img/susan-yin-2JIvboGLeho-unsplash (Thumb).jpg"
  "static/img/ula-kuzma-9i4DHlC80AQ-unsplash (Custom).jpg"
  "static/img/ula-kuzma-9i4DHlC80AQ-unsplash (Small).jpg"
  "static/img/ula-kuzma-9i4DHlC80AQ-unsplash (Thumb).jpg"
)

ALL=("${DEMO[@]}" "${REST[@]}")

total=0
missing=0
for f in "${ALL[@]}"; do
  p="onemuseum/$f"
  if [[ -f "$p" ]]; then
    total=$(( total + $(stat -c%s "$p") ))
  else
    missing=$(( missing + 1 ))
  fi
done

echo "Files listed:  ${#ALL[@]}"
echo "Already gone:  $missing"
printf "Reclaims:      %.1f MB\n" "$(echo "$total / 1048576" | bc -l)"
echo

if [[ $COMMIT -eq 0 ]]; then
  echo "DRY RUN — nothing deleted. Re-run with --commit to proceed."
  exit 0
fi

for f in "${ALL[@]}"; do
  p="onemuseum/$f"
  [[ -f "$p" ]] || continue
  if git rev-parse --git-dir >/dev/null 2>&1 && git ls-files --error-unmatch "$p" >/dev/null 2>&1; then
    git rm -q "$p"
  else
    rm -f "$p"
  fi
done

find onemuseum/static -type d -empty -delete 2>/dev/null || true

echo "Deleted. New static/ size:"
du -sh onemuseum/static
echo
echo "=== VERIFICATION: scanning templates for broken image references ==="
BROKEN=0
while IFS= read -r ref; do
  base=$(basename "$ref")
  if ! find onemuseum/static -name "$base" -print -quit | grep -q .; then
    echo "  MISSING: $ref"
    BROKEN=$(( BROKEN + 1 ))
  fi
done < <(grep -rhoE "(img|assets/img)/[A-Za-z0-9_.() -]+\.(jpg|jpeg|png|gif|svg|webp)" \
           onemuseum/templates onemuseum/snippets onemuseum/static/assets/css 2>/dev/null | sort -u)

if [[ $BROKEN -eq 0 ]]; then
  echo "  OK — no broken references found."
else
  echo
  echo "  $BROKEN broken reference(s). Restore with: git checkout -- <path>"
  exit 1
fi
